/*
  Warnings:

  - You are about to drop the `TB_USUARIO` table. If the table is not empty, all the data it contains will be lost.

*/
-- DropForeignKey
ALTER TABLE "public"."TB_CARRINHO" DROP CONSTRAINT "TB_CARRINHO_SQ_USUARIO_fkey";

-- DropForeignKey
ALTER TABLE "public"."TB_TIPO_USUARIO" DROP CONSTRAINT "TB_TIPO_USUARIO_SQ_USUARIO_fkey";

-- DropTable
DROP TABLE "public"."TB_USUARIO";

-- CreateTable
CREATE TABLE "public"."tb_usuario" (
    "SQ_USUARIO" SERIAL NOT NULL,
    "TP_USUARIO" INTEGER NOT NULL DEFAULT 0,
    "ST_USUARIO" INTEGER NOT NULL,
    "NO_USUARIO" TEXT NOT NULL,
    "EMAIL_USUARIO" TEXT NOT NULL,
    "SENHA_USUARIO" TEXT NOT NULL,
    "DT_CRIACAO" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "DT_EDITADO" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "tb_usuario_pkey" PRIMARY KEY ("SQ_USUARIO")
);

-- CreateIndex
CREATE UNIQUE INDEX "tb_usuario_EMAIL_USUARIO_key" ON "public"."tb_usuario"("EMAIL_USUARIO");

-- AddForeignKey
ALTER TABLE "public"."TB_TIPO_USUARIO" ADD CONSTRAINT "TB_TIPO_USUARIO_SQ_USUARIO_fkey" FOREIGN KEY ("SQ_USUARIO") REFERENCES "public"."tb_usuario"("SQ_USUARIO") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."TB_CARRINHO" ADD CONSTRAINT "TB_CARRINHO_SQ_USUARIO_fkey" FOREIGN KEY ("SQ_USUARIO") REFERENCES "public"."tb_usuario"("SQ_USUARIO") ON DELETE RESTRICT ON UPDATE CASCADE;
