-- CreateTable
CREATE TABLE "public"."TB_USUARIO" (
    "SQ_USUARIO" SERIAL NOT NULL,
    "TP_USUARIO" INTEGER NOT NULL,
    "ST_USUARIO" INTEGER NOT NULL,
    "NO_USUARIO" TEXT NOT NULL,
    "EMAIL_USUARIO" TEXT NOT NULL,
    "DT_CRIACAO" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "DT_EDITADO" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "TB_USUARIO_pkey" PRIMARY KEY ("SQ_USUARIO")
);

-- CreateTable
CREATE TABLE "public"."TB_TIPO_USUARIO" (
    "SQ_TIPO_USUARIO" SERIAL NOT NULL,
    "SQ_USUARIO" INTEGER NOT NULL,
    "SQ_CATEGORIA_USUARIO" INTEGER NOT NULL,

    CONSTRAINT "TB_TIPO_USUARIO_pkey" PRIMARY KEY ("SQ_TIPO_USUARIO")
);

-- CreateTable
CREATE TABLE "public"."TB_CATEGORIA_USUARIO" (
    "SQ_CATEGORIA_USUARIO" SERIAL NOT NULL,
    "NO_CATEGORIA" TEXT NOT NULL,

    CONSTRAINT "TB_CATEGORIA_USUARIO_pkey" PRIMARY KEY ("SQ_CATEGORIA_USUARIO")
);

-- CreateTable
CREATE TABLE "public"."TB_PRODUTO" (
    "SQ_PRODUTO" SERIAL NOT NULL,
    "ST_PRODUTO" INTEGER NOT NULL,
    "NO_PRODUTO" TEXT NOT NULL,
    "QT_PRODUTO" INTEGER NOT NULL,
    "DT_CRIACAO" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "DT_EDITADO" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "TB_PRODUTO_pkey" PRIMARY KEY ("SQ_PRODUTO")
);

-- CreateTable
CREATE TABLE "public"."TB_TIPO_PRODUTO" (
    "SQ_TIPO_PRODUTO" SERIAL NOT NULL,
    "SQ_PRODUTO" INTEGER NOT NULL,
    "SQ_CATEGORIA_PRODUTO" INTEGER NOT NULL,

    CONSTRAINT "TB_TIPO_PRODUTO_pkey" PRIMARY KEY ("SQ_TIPO_PRODUTO")
);

-- CreateTable
CREATE TABLE "public"."TB_CATEGORIA_PRODUTO" (
    "SQ_CATEGORIA_PRODUTO" SERIAL NOT NULL,
    "NO_CATEGORIA" TEXT NOT NULL,

    CONSTRAINT "TB_CATEGORIA_PRODUTO_pkey" PRIMARY KEY ("SQ_CATEGORIA_PRODUTO")
);

-- CreateTable
CREATE TABLE "public"."TB_QTD_PRODUTO" (
    "SQ_QTD_PRODUTO" SERIAL NOT NULL,
    "SQ_PRODUTO" INTEGER NOT NULL,
    "SQ_TAMANHO_PRODUTO" INTEGER NOT NULL,
    "QTD_PRODUTO" INTEGER NOT NULL,

    CONSTRAINT "TB_QTD_PRODUTO_pkey" PRIMARY KEY ("SQ_QTD_PRODUTO")
);

-- CreateTable
CREATE TABLE "public"."TB_TAMANHO_PRODUTO" (
    "SQ_TAMANHO_PRODUTO" SERIAL NOT NULL,
    "NO_CATEGORIA" TEXT NOT NULL,

    CONSTRAINT "TB_TAMANHO_PRODUTO_pkey" PRIMARY KEY ("SQ_TAMANHO_PRODUTO")
);

-- CreateTable
CREATE TABLE "public"."TB_CARRINHO" (
    "SQ_CARRINHO" SERIAL NOT NULL,
    "SQ_USUARIO" INTEGER NOT NULL,

    CONSTRAINT "TB_CARRINHO_pkey" PRIMARY KEY ("SQ_CARRINHO")
);

-- CreateTable
CREATE TABLE "public"."TB_ITENS" (
    "SQ_ITENS" SERIAL NOT NULL,
    "SQ_CARRINHO" INTEGER NOT NULL,
    "SQ_PRODUTO" INTEGER NOT NULL,
    "SQ_TAMANHO_PRODUTO" INTEGER NOT NULL,
    "QTD_PRODUTO" INTEGER NOT NULL,

    CONSTRAINT "TB_ITENS_pkey" PRIMARY KEY ("SQ_ITENS")
);

-- CreateIndex
CREATE UNIQUE INDEX "TB_USUARIO_EMAIL_USUARIO_key" ON "public"."TB_USUARIO"("EMAIL_USUARIO");

-- CreateIndex
CREATE UNIQUE INDEX "TB_TIPO_USUARIO_SQ_USUARIO_key" ON "public"."TB_TIPO_USUARIO"("SQ_USUARIO");

-- CreateIndex
CREATE UNIQUE INDEX "TB_CATEGORIA_USUARIO_NO_CATEGORIA_key" ON "public"."TB_CATEGORIA_USUARIO"("NO_CATEGORIA");

-- CreateIndex
CREATE UNIQUE INDEX "TB_CATEGORIA_PRODUTO_NO_CATEGORIA_key" ON "public"."TB_CATEGORIA_PRODUTO"("NO_CATEGORIA");

-- CreateIndex
CREATE UNIQUE INDEX "TB_CARRINHO_SQ_USUARIO_key" ON "public"."TB_CARRINHO"("SQ_USUARIO");

-- AddForeignKey
ALTER TABLE "public"."TB_TIPO_USUARIO" ADD CONSTRAINT "TB_TIPO_USUARIO_SQ_USUARIO_fkey" FOREIGN KEY ("SQ_USUARIO") REFERENCES "public"."TB_USUARIO"("SQ_USUARIO") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."TB_TIPO_USUARIO" ADD CONSTRAINT "TB_TIPO_USUARIO_SQ_CATEGORIA_USUARIO_fkey" FOREIGN KEY ("SQ_CATEGORIA_USUARIO") REFERENCES "public"."TB_CATEGORIA_USUARIO"("SQ_CATEGORIA_USUARIO") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."TB_TIPO_PRODUTO" ADD CONSTRAINT "TB_TIPO_PRODUTO_SQ_PRODUTO_fkey" FOREIGN KEY ("SQ_PRODUTO") REFERENCES "public"."TB_PRODUTO"("SQ_PRODUTO") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."TB_TIPO_PRODUTO" ADD CONSTRAINT "TB_TIPO_PRODUTO_SQ_CATEGORIA_PRODUTO_fkey" FOREIGN KEY ("SQ_CATEGORIA_PRODUTO") REFERENCES "public"."TB_CATEGORIA_PRODUTO"("SQ_CATEGORIA_PRODUTO") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."TB_QTD_PRODUTO" ADD CONSTRAINT "TB_QTD_PRODUTO_SQ_PRODUTO_fkey" FOREIGN KEY ("SQ_PRODUTO") REFERENCES "public"."TB_PRODUTO"("SQ_PRODUTO") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."TB_QTD_PRODUTO" ADD CONSTRAINT "TB_QTD_PRODUTO_SQ_TAMANHO_PRODUTO_fkey" FOREIGN KEY ("SQ_TAMANHO_PRODUTO") REFERENCES "public"."TB_TAMANHO_PRODUTO"("SQ_TAMANHO_PRODUTO") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."TB_CARRINHO" ADD CONSTRAINT "TB_CARRINHO_SQ_USUARIO_fkey" FOREIGN KEY ("SQ_USUARIO") REFERENCES "public"."TB_USUARIO"("SQ_USUARIO") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."TB_ITENS" ADD CONSTRAINT "TB_ITENS_SQ_CARRINHO_fkey" FOREIGN KEY ("SQ_CARRINHO") REFERENCES "public"."TB_CARRINHO"("SQ_CARRINHO") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."TB_ITENS" ADD CONSTRAINT "TB_ITENS_SQ_PRODUTO_fkey" FOREIGN KEY ("SQ_PRODUTO") REFERENCES "public"."TB_PRODUTO"("SQ_PRODUTO") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."TB_ITENS" ADD CONSTRAINT "TB_ITENS_SQ_TAMANHO_PRODUTO_fkey" FOREIGN KEY ("SQ_TAMANHO_PRODUTO") REFERENCES "public"."TB_TAMANHO_PRODUTO"("SQ_TAMANHO_PRODUTO") ON DELETE RESTRICT ON UPDATE CASCADE;
